### PR TITLE
Dissociate the right checking for the create and the edit buttons

### PR DESCRIPTION
**Pull request by raphj**

### CODE REVIEW

**Comment by ldubost** [comment]
I've created the ticket https://jira.xwiki.org/browse/CRAPP-183

**Comment by vmassol** [comment]
could you put some description in https://jira.xwiki.org/browse/CRAPP-183 to explain the need? thx

**Comment by raphj** [comment]
> @raphj there seems to be some problem with line ending or something like this since I see a lot of lines removed and added without changes

Yes indeed, we fixed xar:format issues wirh @tmortagne yesterday, I force-pushed a commit without the issue.

**Comment by raphj** [comment]
Apparently I can't edit the JIRA ticket.

**Pull request merged**
